"""empty message

Revision ID: 24aac9510ab3
Revises: aa0ad09723c7
Create Date: 2018-08-15 23:39:52.757231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24aac9510ab3'
down_revision = 'aa0ad09723c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('recommends_id', sa.Integer(), nullable=False))
    op.drop_constraint('recommend_ibfk_1', 'recommend', type_='foreignkey')
    op.create_foreign_key(None, 'recommend', 'users', ['recommends_id'], ['id'])
    op.drop_column('recommend', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('followed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.create_foreign_key('recommend_ibfk_1', 'recommend', 'users', ['followed_id'], ['id'])
    op.drop_column('recommend', 'recommends_id')
    # ### end Alembic commands ###
