"""empty message

Revision ID: 3b042c12d85e
Revises: e0a5da4798cf
Create Date: 2018-10-28 17:04:08.383794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b042c12d85e'
down_revision = 'e0a5da4798cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('parent', sa.Integer(), nullable=True))
    op.drop_constraint('categorys_ibfk_1', 'categorys', type_='foreignkey')
    op.create_foreign_key(None, 'categorys', 'categorys', ['parent'], ['id'])
    op.drop_column('categorys', 'parent_id')
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('ean', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('hot', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_sell', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('main_photo', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('note', sa.UnicodeText(), nullable=True))
    op.add_column('products', sa.Column('special_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('unit', sa.Integer(), nullable=True))
    op.drop_column('products', 'thumbnail')
    op.add_column('users', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('integral', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'integral')
    op.drop_column('users', 'coins')
    op.add_column('products', sa.Column('thumbnail', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('products', 'unit')
    op.drop_column('products', 'special_price')
    op.drop_column('products', 'note')
    op.drop_column('products', 'main_photo')
    op.drop_column('products', 'is_sell')
    op.drop_column('products', 'hot')
    op.drop_column('products', 'ean')
    op.drop_column('products', 'created_at')
    op.add_column('categorys', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categorys', type_='foreignkey')
    op.create_foreign_key('categorys_ibfk_1', 'categorys', 'categorys', ['parent_id'], ['id'])
    op.drop_column('categorys', 'parent')
    # ### end Alembic commands ###
