"""empty message

Revision ID: 88cf82c03451
Revises: d61c3c0d0a4a
Create Date: 2018-08-05 21:38:07.000959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88cf82c03451'
down_revision = 'd61c3c0d0a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_center', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_column('users', 'is_center')
    # ### end Alembic commands ###
