"""empty message

Revision ID: 9c1724203d00
Revises: d0e3e2237dc4
Create Date: 2018-08-15 23:06:01.609217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1724203d00'
down_revision = 'd0e3e2237dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_buys', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('parent_center', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_center'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_center')
    op.drop_column('products_buys', 'created_at')
    # ### end Alembic commands ###
