"""empty message

Revision ID: aa0ad09723c7
Revises: 637e45c7afc4
Create Date: 2018-08-15 23:39:09.026916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa0ad09723c7'
down_revision = '637e45c7afc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('recommender_id', sa.Integer(), nullable=False))
    op.drop_constraint('recommend_ibfk_2', 'recommend', type_='foreignkey')
    op.create_foreign_key(None, 'recommend', 'users', ['recommender_id'], ['id'])
    op.drop_column('recommend', 'follower_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend', sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.create_foreign_key('recommend_ibfk_2', 'recommend', 'users', ['follower_id'], ['id'])
    op.drop_column('recommend', 'recommender_id')
    # ### end Alembic commands ###
