"""empty message

Revision ID: d61c3c0d0a4a
Revises: 7ebcccae9680
Create Date: 2018-08-01 11:58:00.242305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd61c3c0d0a4a'
down_revision = '7ebcccae9680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_ibfk_1', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_ibfk_1', 'roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
