"""empty message

Revision ID: e7c280ab61a7
Revises: 7c3433c4ef01
Create Date: 2018-10-15 21:15:33.530432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7c280ab61a7'
down_revision = '7c3433c4ef01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('products_id', sa.Integer(), nullable=True),
    sa.Column('consignee', sa.String(length=30), nullable=True),
    sa.Column('consignee_phone', sa.String(length=30), nullable=True),
    sa.Column('consignee_address', sa.String(length=200), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay_type', sa.String(length=100), nullable=True),
    sa.Column('buy_type', sa.String(length=100), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products_buys')
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')
    op.add_column('products', sa.Column('thumbnail', sa.String(length=200), nullable=True))
    op.add_column('recommend', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('sysconfig', sa.Column('close_register_user_message', sa.String(length=500), nullable=True))
    op.add_column('sysconfig', sa.Column('close_website_message', sa.String(length=500), nullable=True))
    op.add_column('sysconfig', sa.Column('withdraw_money', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               nullable=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=30), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_column('sysconfig', 'withdraw_money')
    op.drop_column('sysconfig', 'close_website_message')
    op.drop_column('sysconfig', 'close_register_user_message')
    op.drop_column('recommend', 'id')
    op.drop_column('products', 'thumbnail')
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'roles', ['name'], unique=True)
    op.create_table('products_buys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('products_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['products_id'], [u'products.id'], name=u'products_buys_ibfk_1'),
    sa.ForeignKeyConstraint(['users_id'], [u'users.id'], name=u'products_buys_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
